import type { Property } from "@/types/property";

export const SEED_PROPERTIES: Property[] = [
  {
    id: "prop-1",
    tenantId: "t1",
    tenantName: "Inmobiliaria Sur",
    title: "Departamento luminoso en Palermo",
    description:
      "Amplio 3 ambientes con balcón, cocina integrada y amenities en el edificio. A metros de Plaza Serrano.",
    operationType: "RENT",
    propertyType: "APARTMENT",
    status: "ACTIVE",
    price: 850000,
    currency: "ARS",
    coveredArea: 72,
    totalArea: 78,
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    address: "Gorriti 4200",
    neighborhood: "Palermo",
    city: "Buenos Aires",
    lat: -34.5889,
    lng: -58.4306,
    images: [
      {
        id: "img-1",
        url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
        order: 0,
        isCover: true,
      },
    ],
    amenities: ["Pileta", "SUM", "Seguridad 24h"],
  },
  {
    id: "prop-2",
    tenantId: "t2",
    tenantName: "Centro Propiedades",
    title: "Casa con jardín en San Isidro",
    description:
      "Casa de 4 ambientes en barrio residencial, garage para 2 autos y parrilla.",
    operationType: "SALE",
    propertyType: "HOUSE",
    status: "ACTIVE",
    price: 285000,
    currency: "USD",
    coveredArea: 180,
    totalArea: 420,
    rooms: 4,
    bedrooms: 3,
    bathrooms: 2,
    address: "Av. del Libertador 15200",
    neighborhood: "San Isidro",
    city: "San Isidro",
    lat: -34.4732,
    lng: -58.5271,
    images: [
      {
        id: "img-2",
        url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
        order: 0,
        isCover: true,
      },
    ],
    amenities: ["Jardín", "Parrilla", "Garage"],
  },
  {
    id: "prop-3",
    tenantId: "t1",
    tenantName: "Inmobiliaria Sur",
    title: "PH reciclado en Villa Crespo",
    description: "Dos plantas, patio propio y excelente conectividad con subte.",
    operationType: "SALE",
    propertyType: "PH",
    status: "ACTIVE",
    price: 195000,
    currency: "USD",
    coveredArea: 95,
    totalArea: 110,
    rooms: 3,
    bedrooms: 2,
    bathrooms: 2,
    address: "Corrientes 5200",
    neighborhood: "Villa Crespo",
    city: "Buenos Aires",
    lat: -34.5985,
    lng: -58.437,
    images: [
      {
        id: "img-3",
        url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
        order: 0,
        isCover: true,
      },
    ],
    amenities: ["Patio", "Terraza"],
  },
  {
    id: "prop-4",
    tenantId: "t3",
    tenantName: "Delta Lotes",
    title: "Lote en country con acceso asfaltado",
    description: "Terreno de 800 m² en loteo cerrado con servicios y seguridad.",
    operationType: "SALE",
    propertyType: "LAND",
    status: "ACTIVE",
    price: 45000,
    currency: "USD",
    coveredArea: null,
    totalArea: 800,
    rooms: null,
    bedrooms: null,
    bathrooms: null,
    address: "Ruta 58 km 12",
    neighborhood: "Canning",
    city: "Ezeiza",
    lat: -34.855,
    lng: -58.512,
    images: [
      {
        id: "img-4",
        url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
        order: 0,
        isCover: true,
      },
    ],
    amenities: ["Seguridad", "Club house"],
  },
  {
    id: "prop-5",
    tenantId: "t2",
    tenantName: "Centro Propiedades",
    title: "Monoambiente en Microcentro",
    description: "Ideal inversión o primera vivienda, amoblado y listo para habitar.",
    operationType: "RENT",
    propertyType: "APARTMENT",
    status: "ACTIVE",
    price: 520000,
    currency: "ARS",
    coveredArea: 38,
    totalArea: 38,
    rooms: 1,
    bedrooms: 0,
    bathrooms: 1,
    address: "Reconquista 600",
    neighborhood: "Microcentro",
    city: "Buenos Aires",
    lat: -34.6037,
    lng: -58.3719,
    images: [
      {
        id: "img-5",
        url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
        order: 0,
        isCover: true,
      },
    ],
    amenities: ["Amoblado", "Laundry"],
  },
  {
    id: "prop-6",
    tenantId: "t3",
    tenantName: "Delta Lotes",
    title: "Local a la calle en Belgrano",
    description: "Vidriera amplia, ideal gastronomía o retail. Expensas moderadas.",
    operationType: "RENT",
    propertyType: "COMMERCIAL_LOCAL",
    status: "ACTIVE",
    price: 1200000,
    currency: "ARS",
    coveredArea: 65,
    totalArea: 65,
    rooms: 2,
    bedrooms: null,
    bathrooms: 1,
    address: "Cabildo 2100",
    neighborhood: "Belgrano",
    city: "Buenos Aires",
    lat: -34.563,
    lng: -58.458,
    images: [
      {
        id: "img-6",
        url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
        order: 0,
        isCover: true,
      },
    ],
    amenities: ["Vidriera", "Depósito"],
  },
  {
    id: "prop-7",
    tenantId: "t1",
    tenantName: "Inmobiliaria Sur",
    title: "Oficina premium en Puerto Madero",
    description: "Piso alto con vista al río, 3 privados y recepción.",
    operationType: "RENT",
    propertyType: "OFFICE",
    status: "ACTIVE",
    price: 2800,
    currency: "USD",
    coveredArea: 120,
    totalArea: 120,
    rooms: 4,
    bedrooms: null,
    bathrooms: 2,
    address: "Azucena Villaflor 400",
    neighborhood: "Puerto Madero",
    city: "Buenos Aires",
    lat: -34.611,
    lng: -58.362,
    images: [
      {
        id: "img-7",
        url: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80",
        order: 0,
        isCover: true,
      },
    ],
    amenities: ["Cocheras", "Seguridad", "HVAC"],
  },
  {
    id: "prop-8",
    tenantId: "t2",
    tenantName: "Centro Propiedades",
    title: "Duplex en Nordelta",
    description: "4 ambientes en barrio cerrado, pileta comunitaria y canchas.",
    operationType: "SALE",
    propertyType: "HOUSE",
    status: "ACTIVE",
    price: 320000,
    currency: "USD",
    coveredArea: 145,
    totalArea: 220,
    rooms: 4,
    bedrooms: 3,
    bathrooms: 3,
    address: "Los Castores 1200",
    neighborhood: "Nordelta",
    city: "Tigre",
    lat: -34.412,
    lng: -58.652,
    images: [
      {
        id: "img-8",
        url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
        order: 0,
        isCover: true,
      },
    ],
    amenities: ["Pileta", "Club house", "Seguridad"],
  },
];

export function getPropertyById(id: string): Property | undefined {
  return SEED_PROPERTIES.find((p) => p.id === id);
}

export const CITIES = [...new Set(SEED_PROPERTIES.map((p) => p.city))].sort();
